### ISSUE TITLE
Suggestion to create tempory files used by the converter  in the user area's temp folder  

### ISSUE THREAD

**Issue by wi-fr** [andrei-m-code/net-core-html-to-image#15]
Thanks for your very appealing tool.

When launching it from Windows PowerShell, it attempts creating a temporary file in  PowerShell's installation folder. This folder requires elevation to write to. May I suggest creating the temporary file in the user area instead.

# Steps to reproduce:

Add-Type -path 'C:\Program Files\PackageManagement\NuGet\Packages\CoreHtmlToImage.1.0.5\lib\netstandard2.0\CoreHtmlToImage.dll' -PassThru
$converter = [CoreHtmlToImage.HtmlConverter]::new()
$converter.FromHtmlString('<div>Hello World!</div>', 100)

Exception calling "FromHtmlString" with "2" argument(s): "Access to the path 
'C:\WINDOWS\system32\WindowsPowerShell\v1.0\eec70834-fbf7-47dc-8ae6-dd55a6e970dc.html' is denied."

**Comment by andrei-m-code** [comment]
@wi-fr it creates an .exe file in the working directory. Apparently for powershell system32 is a working directory. I think it is ok and as you pointed out you can use elevated permissions. I wouldn't expect the package to be used from the command line. I suggest you to use wkhtmltoimage.exe directly instead of using my library as that is what I use under the hood.

**Comment by wi-fr** [comment]
Thanks for the feedback. I used it from the PowerShell command line just to illustrate the issue. As you suggested, I switched over to wkhtmltoimage.exe.
